# 规则配置示例：每分钟请求次数阈值
rules:
  - name: high_freq_login
    type: frequency
    threshold_per_minute: 10
    whitelist: ./config/whitelist.txt

  - name: path_probe_freq
    type: path_probe_freq
    sensitive_paths:
      - /admin
      - /login
      - /phpmyadmin
    threshold: 10
    whitelist: ./config/whitelist.txt

  - name: path_probe_detect
    type: path_probe
    sensitive_paths:
      - /admin
      - /login
      - /phpmyadmin
    threshold: 3
    whitelist: ./config/whitelist.txt
